### ISSUE TITLE
Accepting new words

### ISSUE THREAD

**Issue by KennethSweezy** [keithieopia/crappy-cryptonyms#1]
Are you willing to accept new words into the project?

**Comment by keithieopia** [comment]
Yes absolutely. Any form of contribution is highly appreciated.

The code is pretty self-explanatory, there's two wordlist files:

* [js/adjectives.js](https://github.com/keithieopia/crappy-cryptonyms/blob/master/js/adjectives.js)
* [js/nouns.js](https://github.com/keithieopia/crappy-cryptonyms/blob/master/js/nouns.js)

I've tried to avoid outright offensive words or sexual innuendo, but if you look at the wordlists you can see they're not very strict guidelines.

**Comment by KennethSweezy** [comment]
Ok, thanks for answering my question.

I have opened a PR: #2
